# Generated by Django 5.0.6 on 2024-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcs', models.TextField()),
                ('date', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('fcs_commissions1', models.TextField()),
                ('commisions_status1', models.TextField()),
                ('fcs_commissions2', models.TextField()),
                ('commisions_status2', models.TextField()),
                ('fcs_commissions3', models.TextField()),
                ('commisions_status3', models.TextField()),
                ('responsible_electrical_safety', models.TextField()),
                ('reason_for_check', models.TextField()),
                ('antifire_reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('number_of_driver_program', models.CharField(max_length=1)),
                ('electrical_safety_group', models.CharField(max_length=3)),
                ('work_exp', models.CharField(max_length=2)),
                ('session', models.TextField()),
            ],
        ),
    ]
